// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyCommandToClipboard(arg1, arg2) {
  return window['go']['main']['App']['CopyCommandToClipboard'](arg1, arg2);
}

export function GetCommandsByTerminal(arg1) {
  return window['go']['main']['App']['GetCommandsByTerminal'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
