// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {main} from '../models';

export function CopyCommandToClipboard(arg1:string,arg2:string):Promise<void>;

export function GetCommandsByTerminal(arg1:string):Promise<Array<session.SuggestedCommand>>;

export function Greet(arg1:string):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<main.SendMessageResponse>;
